"""empty message

Revision ID: 5257a1ba03b0
Revises: d093ec1c823c
Create Date: 2021-09-09 11:48:28.016682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5257a1ba03b0'
down_revision = 'd093ec1c823c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('color', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
