"""empty message

Revision ID: d093ec1c823c
Revises: 
Create Date: 2021-09-09 11:40:35.986233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd093ec1c823c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('color')
    op.add_column('user', sa.Column('colors', sa.String(), nullable=True))
    op.drop_column('user', 'color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('color', sa.VARCHAR(), nullable=True))
    op.drop_column('user', 'colors')
    op.create_table('color',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('colorname', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
